export const initialProjects = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description: "A full-stack e-commerce solution with React and Node.js",
    author: "Jane Smith",
    date: "2023-10-15",
    status: "submitted",
    category: "Web Application",
  },
  {
    id: 2,
    title: "Health Tracker App",
    description: "Mobile application for tracking health metrics and workouts",
    author: "John Doe",
    date: "2023-10-10",
    status: "in review",
    category: "Mobile Application",
  },
  {
    id: 3,
    title: "AI Photo Enhancer",
    description: "Machine learning tool for enhancing image quality automatically",
    author: "Alex Johnson",
    date: "2023-10-05",
    status: "approved",
    category: "Machine Learning",
  },
  {
    id: 4,
    title: "Task Management System",
    description: "Productivity tool for teams to manage tasks and projects",
    author: "Sarah Williams",
    date: "2023-09-28",
    status: "submitted",
    category: "Web Application",
  },
  {
    id: 5,
    title: "Smart Home Controller",
    description: "IoT system for controlling home devices from a central hub",
    author: "Michael Brown",
    date: "2023-09-20",
    status: "approved",
    category: "IoT",
  },
  {
    id: 6,
    title: "Language Learning Game",
    description: "Interactive game for learning new languages through play",
    author: "Emily Chen",
    date: "2023-09-15",
    status: "in review",
    category: "Game Development",
  },
];
